export const iconUrls = [
  "/svgs/blue-atom.svg",
  "/svgs/long-yellow-arrow.svg",
  "/svgs/multi-color-f.svg",
  "/svgs/pink-triangle.svg",
  "/svgs/pointer.svg",
  "/svgs/purple-circle.svg",
  "/svgs/purple-rhomboid.svg",
  "/svgs/s-block.svg",
  "/svgs/yellow-dots.svg",
  "/svgs/yellow-oblong.svg",
  "/svgs/yellow-smile.svg",
  "/svgs/circle-arrow.svg",
  "/svgs/blue-cloud.svg",
  "/svgs/purple-straight-face.svg",
  "/svgs/pink-arrow.svg",
  "/svgs/angular.svg",
  "/svgs/v-face.svg",
  "/svgs/orange-rhomboid.svg",
  "/svgs/pink-play.svg",
].sort(() => Math.random() - 0.5);
